package com.app.cbouix.sodapp.DataAccess.DataBase;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table ARTICULO.
 */
public class Articulo {

    private Long id;
    private String Codigo;
    private String Nombre;
    private Double Precio;
    private String UnidadMedida;

    public Articulo() {
    }

    public Articulo(Long id) {
        this.id = id;
    }

    public Articulo(Long id, String Codigo, String Nombre, Double Precio, String UnidadMedida) {
        this.id = id;
        this.Codigo = Codigo;
        this.Nombre = Nombre;
        this.Precio = Precio;
        this.UnidadMedida = UnidadMedida;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getCodigo() {
        return Codigo;
    }

    public void setCodigo(String Codigo) {
        this.Codigo = Codigo;
    }

    public String getNombre() {
        return Nombre;
    }

    public void setNombre(String Nombre) {
        this.Nombre = Nombre;
    }

    public Double getPrecio() {
        return Precio;
    }

    public void setPrecio(Double Precio) {
        this.Precio = Precio;
    }

    public String getUnidadMedida() {
        return UnidadMedida;
    }

    public void setUnidadMedida(String UnidadMedida) {
        this.UnidadMedida = UnidadMedida;
    }

}
