package com.app.cbouix.sodapp.DataAccess.DataBase;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table COBRANZA.
 */
public class Cobranza {

    private Long id;
    private Boolean IsRemito;
    private String Emision;
    private String Numero;
    private Double Importe;
    private Double ImporteAplicado;
    private Integer ClienteId;
    private String ClienteCod;
    private String ClienteNombre;
    private Integer DomicilioId;
    private String Domicilio;
    private Integer RepartidorId;

    public Cobranza() {
    }

    public Cobranza(Long id) {
        this.id = id;
    }

    public Cobranza(Long id, Boolean IsRemito, String Emision, String Numero, Double Importe, Double ImporteAplicado, Integer ClienteId, String ClienteCod, String ClienteNombre, Integer DomicilioId, String Domicilio, Integer RepartidorId) {
        this.id = id;
        this.IsRemito = IsRemito;
        this.Emision = Emision;
        this.Numero = Numero;
        this.Importe = Importe;
        this.ImporteAplicado = ImporteAplicado;
        this.ClienteId = ClienteId;
        this.ClienteCod = ClienteCod;
        this.ClienteNombre = ClienteNombre;
        this.DomicilioId = DomicilioId;
        this.Domicilio = Domicilio;
        this.RepartidorId = RepartidorId;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Boolean getIsRemito() {
        return IsRemito;
    }

    public void setIsRemito(Boolean IsRemito) {
        this.IsRemito = IsRemito;
    }

    public String getEmision() {
        return Emision;
    }

    public void setEmision(String Emision) {
        this.Emision = Emision;
    }

    public String getNumero() {
        return Numero;
    }

    public void setNumero(String Numero) {
        this.Numero = Numero;
    }

    public Double getImporte() {
        return Importe;
    }

    public void setImporte(Double Importe) {
        this.Importe = Importe;
    }

    public Double getImporteAplicado() {
        return ImporteAplicado;
    }

    public void setImporteAplicado(Double ImporteAplicado) {
        this.ImporteAplicado = ImporteAplicado;
    }

    public Integer getClienteId() {
        return ClienteId;
    }

    public void setClienteId(Integer ClienteId) {
        this.ClienteId = ClienteId;
    }

    public String getClienteCod() {
        return ClienteCod;
    }

    public void setClienteCod(String ClienteCod) {
        this.ClienteCod = ClienteCod;
    }

    public String getClienteNombre() {
        return ClienteNombre;
    }

    public void setClienteNombre(String ClienteNombre) {
        this.ClienteNombre = ClienteNombre;
    }

    public Integer getDomicilioId() {
        return DomicilioId;
    }

    public void setDomicilioId(Integer DomicilioId) {
        this.DomicilioId = DomicilioId;
    }

    public String getDomicilio() {
        return Domicilio;
    }

    public void setDomicilio(String Domicilio) {
        this.Domicilio = Domicilio;
    }

    public Integer getRepartidorId() {
        return RepartidorId;
    }

    public void setRepartidorId(Integer RepartidorId) {
        this.RepartidorId = RepartidorId;
    }

}
