package com.app.cbouix.sodapp.DataAccess.DataBase;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig clienteDaoConfig;
    private final DaoConfig articuloDaoConfig;
    private final DaoConfig remitoLinDaoConfig;
    private final DaoConfig remitoDaoConfig;
    private final DaoConfig cobranzaLinDaoConfig;
    private final DaoConfig cobranzaDaoConfig;

    private final ClienteDao clienteDao;
    private final ArticuloDao articuloDao;
    private final RemitoLinDao remitoLinDao;
    private final RemitoDao remitoDao;
    private final CobranzaLinDao cobranzaLinDao;
    private final CobranzaDao cobranzaDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        clienteDaoConfig = daoConfigMap.get(ClienteDao.class).clone();
        clienteDaoConfig.initIdentityScope(type);

        articuloDaoConfig = daoConfigMap.get(ArticuloDao.class).clone();
        articuloDaoConfig.initIdentityScope(type);

        remitoLinDaoConfig = daoConfigMap.get(RemitoLinDao.class).clone();
        remitoLinDaoConfig.initIdentityScope(type);

        remitoDaoConfig = daoConfigMap.get(RemitoDao.class).clone();
        remitoDaoConfig.initIdentityScope(type);

        cobranzaLinDaoConfig = daoConfigMap.get(CobranzaLinDao.class).clone();
        cobranzaLinDaoConfig.initIdentityScope(type);

        cobranzaDaoConfig = daoConfigMap.get(CobranzaDao.class).clone();
        cobranzaDaoConfig.initIdentityScope(type);

        clienteDao = new ClienteDao(clienteDaoConfig, this);
        articuloDao = new ArticuloDao(articuloDaoConfig, this);
        remitoLinDao = new RemitoLinDao(remitoLinDaoConfig, this);
        remitoDao = new RemitoDao(remitoDaoConfig, this);
        cobranzaLinDao = new CobranzaLinDao(cobranzaLinDaoConfig, this);
        cobranzaDao = new CobranzaDao(cobranzaDaoConfig, this);

        registerDao(Cliente.class, clienteDao);
        registerDao(Articulo.class, articuloDao);
        registerDao(RemitoLin.class, remitoLinDao);
        registerDao(Remito.class, remitoDao);
        registerDao(CobranzaLin.class, cobranzaLinDao);
        registerDao(Cobranza.class, cobranzaDao);
    }
    
    public void clear() {
        clienteDaoConfig.getIdentityScope().clear();
        articuloDaoConfig.getIdentityScope().clear();
        remitoLinDaoConfig.getIdentityScope().clear();
        remitoDaoConfig.getIdentityScope().clear();
        cobranzaLinDaoConfig.getIdentityScope().clear();
        cobranzaDaoConfig.getIdentityScope().clear();
    }

    public ClienteDao getClienteDao() {
        return clienteDao;
    }

    public ArticuloDao getArticuloDao() {
        return articuloDao;
    }

    public RemitoLinDao getRemitoLinDao() {
        return remitoLinDao;
    }

    public RemitoDao getRemitoDao() {
        return remitoDao;
    }

    public CobranzaLinDao getCobranzaLinDao() {
        return cobranzaLinDao;
    }

    public CobranzaDao getCobranzaDao() {
        return cobranzaDao;
    }

}
