package com.app.cbouix.sodapp.DataAccess.DataBase;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table REMITO.
 */
public class Remito {

    private Long id;
    private Long CobranzaId;
    private String Emision;
    private String Numero;
    private Double Importe;
    private Integer ClienteId;
    private String ClienteCod;
    private String ClienteNombre;
    private Integer DomicilioId;
    private String Direccion;
    private Integer ListPrecioId;
    private Integer RepartidorId;

    public Remito() {
    }

    public Remito(Long id) {
        this.id = id;
    }

    public Remito(Long id, Long CobranzaId, String Emision, String Numero, Double Importe, Integer ClienteId, String ClienteCod, String ClienteNombre, Integer DomicilioId, String Direccion, Integer ListPrecioId, Integer RepartidorId) {
        this.id = id;
        this.CobranzaId = CobranzaId;
        this.Emision = Emision;
        this.Numero = Numero;
        this.Importe = Importe;
        this.ClienteId = ClienteId;
        this.ClienteCod = ClienteCod;
        this.ClienteNombre = ClienteNombre;
        this.DomicilioId = DomicilioId;
        this.Direccion = Direccion;
        this.ListPrecioId = ListPrecioId;
        this.RepartidorId = RepartidorId;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getCobranzaId() {
        return CobranzaId;
    }

    public void setCobranzaId(Long CobranzaId) {
        this.CobranzaId = CobranzaId;
    }

    public String getEmision() {
        return Emision;
    }

    public void setEmision(String Emision) {
        this.Emision = Emision;
    }

    public String getNumero() {
        return Numero;
    }

    public void setNumero(String Numero) {
        this.Numero = Numero;
    }

    public Double getImporte() {
        return Importe;
    }

    public void setImporte(Double Importe) {
        this.Importe = Importe;
    }

    public Integer getClienteId() {
        return ClienteId;
    }

    public void setClienteId(Integer ClienteId) {
        this.ClienteId = ClienteId;
    }

    public String getClienteCod() {
        return ClienteCod;
    }

    public void setClienteCod(String ClienteCod) {
        this.ClienteCod = ClienteCod;
    }

    public String getClienteNombre() {
        return ClienteNombre;
    }

    public void setClienteNombre(String ClienteNombre) {
        this.ClienteNombre = ClienteNombre;
    }

    public Integer getDomicilioId() {
        return DomicilioId;
    }

    public void setDomicilioId(Integer DomicilioId) {
        this.DomicilioId = DomicilioId;
    }

    public String getDireccion() {
        return Direccion;
    }

    public void setDireccion(String Direccion) {
        this.Direccion = Direccion;
    }

    public Integer getListPrecioId() {
        return ListPrecioId;
    }

    public void setListPrecioId(Integer ListPrecioId) {
        this.ListPrecioId = ListPrecioId;
    }

    public Integer getRepartidorId() {
        return RepartidorId;
    }

    public void setRepartidorId(Integer RepartidorId) {
        this.RepartidorId = RepartidorId;
    }

}
