package com.app.cbouix.sodapp.DataAccess.DataBase;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table REMITO_LIN.
 */
public class RemitoLin {

    private Long id;
    private Long RemitoId;
    private Integer ArticuloId;
    private String ArticuloCod;
    private String ArticuloNombre;
    private Integer Cantidad;
    private String UnMedidaCod;
    private String TipoCod;
    private Integer Signo;
    private Double Precio;

    public RemitoLin() {
    }

    public RemitoLin(Long id) {
        this.id = id;
    }

    public RemitoLin(Long id, Long RemitoId, Integer ArticuloId, String ArticuloCod, String ArticuloNombre, Integer Cantidad, String UnMedidaCod, String TipoCod, Integer Signo, Double Precio) {
        this.id = id;
        this.RemitoId = RemitoId;
        this.ArticuloId = ArticuloId;
        this.ArticuloCod = ArticuloCod;
        this.ArticuloNombre = ArticuloNombre;
        this.Cantidad = Cantidad;
        this.UnMedidaCod = UnMedidaCod;
        this.TipoCod = TipoCod;
        this.Signo = Signo;
        this.Precio = Precio;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getRemitoId() {
        return RemitoId;
    }

    public void setRemitoId(Long RemitoId) {
        this.RemitoId = RemitoId;
    }

    public Integer getArticuloId() {
        return ArticuloId;
    }

    public void setArticuloId(Integer ArticuloId) {
        this.ArticuloId = ArticuloId;
    }

    public String getArticuloCod() {
        return ArticuloCod;
    }

    public void setArticuloCod(String ArticuloCod) {
        this.ArticuloCod = ArticuloCod;
    }

    public String getArticuloNombre() {
        return ArticuloNombre;
    }

    public void setArticuloNombre(String ArticuloNombre) {
        this.ArticuloNombre = ArticuloNombre;
    }

    public Integer getCantidad() {
        return Cantidad;
    }

    public void setCantidad(Integer Cantidad) {
        this.Cantidad = Cantidad;
    }

    public String getUnMedidaCod() {
        return UnMedidaCod;
    }

    public void setUnMedidaCod(String UnMedidaCod) {
        this.UnMedidaCod = UnMedidaCod;
    }

    public String getTipoCod() {
        return TipoCod;
    }

    public void setTipoCod(String TipoCod) {
        this.TipoCod = TipoCod;
    }

    public Integer getSigno() {
        return Signo;
    }

    public void setSigno(Integer Signo) {
        this.Signo = Signo;
    }

    public Double getPrecio() {
        return Precio;
    }

    public void setPrecio(Double Precio) {
        this.Precio = Precio;
    }

}
